### ISSUE TITLE
Flame 1.0.0

### ISSUE THREAD

**Issue by Shentia** [PacktPublishing/Building-Games-with-Flutter#3]
I got an error
    addHitbox(HitboxRectangle());
and 
    renderHitboxes(canvas, paint: squarePaint);
then I changed to flame 1.5.0
and using 
    addHitbox(HitboxRectangle()); ->  add(RectangleHitbox());
but I don't know how can change
    renderHitboxes(canvas, paint: squarePaint);
into lame 1.5.0  and got an error 

	"message": "The named parameter 'paint' isn't defined.\nTry correcting the name to an existing named parameter's name, or defining a named parameter with the name 'paint'.",

Thanks

**Comment by saurabhk710** [comment]
HI @pteale can you please help @Shentia with this issue ?

**Comment by pteale** [comment]
The book shipped with support for 1.0.0 of Flame which was the current library at the time of the book launch
To follow along with the book I would keep this value at 1.0.0 for now, athough I am planning to review this repos code against the latest version of Flame in February, and will post an update in the README file once this done.

**Comment by Shentia** [comment]
Oh I see 
Thanks Pteale 🫡
