### ISSUE TITLE
window comes from where?

### ISSUE THREAD

**Issue by Narven** [PacktPublishing/Building-Games-with-Flutter#4]
"window" is supose to come from where?

after 10 seconds of reading a book

https://github.com/PacktPublishing/Building-Games-with-Flutter/blob/main/chapter01/lib/main.dart#L40

**Comment by JoRiviera** [comment]
Hi there, I was puzzled at first too, it comes from the "dart:ui" import, must be some kind of global (I'm a Dart and Flutter Newbie) from this module.

**Comment by pteale** [comment]
Yes it's a global value passed to the fromWindow method, in this case used for calculating the screen dimensions
