### ISSUE TITLE
with Loadable ???

### ISSUE THREAD

**Issue by Ramzi-dr** [PacktPublishing/Building-Games-with-Flutter#5]
class GoldRush with Loadable, Game{}
error getting Loadable class 
![Unbenannt](https://user-images.githubusercontent.com/82414280/211164027-134ed2ba-30e5-46f7-bf1b-1ba01c609028.PNG)

**Comment by pteale** [comment]
What version of the Flame library are you using in your pubspec file?

**Comment by AYJF** [comment]
I have the same issue I'm using flame version 1.6

**Comment by pteale** [comment]
The book currently only works with v1.0 of Flame, but I am working on an update to update this to 1.6
For now if you set the version to 1.0 Loadable will work
