### ISSUE TITLE
Missing Assets and Chapter 3

### ISSUE THREAD

**Issue by kleyersoma** [PacktPublishing/Building-Games-with-Flutter#7]
Hello, the assets needed for chapter 2 are missing from the branch related to that chapter also there isn't a branch for chapter 3, would be of great help if you update the branch of chapter 2 with the respective missing assets.

**Comment by pteale** [comment]
Hi, there is no assets for chapter 2. In Chapter 2 we simply animate a rectangle that we draw on screen, so no images or other assets are needed for this
