### ISSUE TITLE
Flame package version...

### ISSUE THREAD

**Issue by yunikim77** [PacktPublishing/Building-Games-with-Flutter#8]
I wonder if you have any plans to update the Flame package version applied to this repo to the latest version(1.6.0).
If you have a plan, when will you update it?
There is a big difference between the Flame 1.0.0 version and the current version,
and I think it is better to study the latest version as much as possible for the future.

**Comment by pteale** [comment]
Thanks for your question
I am currently updating the books code to Flame v1.6 and will update the README on the repo when this is complete
